### ISSUE TITLE
CRITICAL 'module_name' in modules

### ISSUE THREAD

**Issue by vittobe** [michaelmiklis/loxberry-plugin-netatmo-weather#3]
Hello Michael,

In a first step I was able to fix the issue with my password containing a % sign, 
now I run into a new issue:

from /plugins/netatmo-weather/netatmo-weather.log

```
2023-10-27 14:45:04 urllib3.connectionpool DEBUG https://auth.netatmo.com:443 "GET /en-us/access/keychain?next_url=https%3A%2F%2Fmy.netatmo.com%2Fapp%2Fstation%2F HTTP/1.1" 200 None
2023-10-27 14:45:04 root INFO Successfully logged in using username abcd@xyz.org and password xxxxxxxxxx to https://auth.netatmo.com/access/postlogin
2023-10-27 14:45:04 root INFO Found netatmocomaccess_token value 59c6xxxxxxxxxx0a1%7Cxxxxxxxxxxxxxxxxxxxxxxx23 in response from https://auth.netatmo.com/access/postlogin
2023-10-27 14:45:04 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): api.netatmo.com:443
2023-10-27 14:45:05 urllib3.connectionpool DEBUG https://api.netatmo.com:443 "POST /api/getstationsdata HTTP/1.1" 200 None
2023-10-27 14:45:05 root INFO Querying queried API https://api.netatmo.com/api/getstationsdata
2023-10-27 14:45:05 root INFO Successfully queried queried API https://api.netatmo.com/api/getstationsdata
2023-10-27 14:45:05 root INFO Home.Indoor.wifi_status=67
2023-10-27 14:45:05 root INFO Home.Indoor.reachable=1
2023-10-27 14:45:05 root INFO Home.Indoor.time_utc=467649477
2023-10-27 14:45:05 root INFO Home.Indoor.Temperature=20.5
2023-10-27 14:45:05 root INFO Home.Indoor.CO2=1497
2023-10-27 14:45:05 root INFO Home.Indoor.Humidity=64
2023-10-27 14:45:05 root INFO Home.Indoor.Noise=39
2023-10-27 14:45:05 root INFO Home.Indoor.Pressure=997.1
2023-10-27 14:45:05 root INFO Home.Indoor.AbsolutePressure=996.2
2023-10-27 14:45:05 root INFO Home.Indoor.min_temp=19.3
2023-10-27 14:45:05 root INFO Home.Indoor.max_temp=21.3
2023-10-27 14:45:05 root INFO Home.Indoor.date_max_temp=467638914
2023-10-27 14:45:05 root INFO Home.Indoor.date_min_temp=467625286
2023-10-27 14:45:05 root INFO Home.Indoor.temp_trend=1
2023-10-27 14:45:05 root INFO Home.Indoor.pressure_trend=1
2023-10-27 14:45:05 root INFO Home.Outdoor.battery_percent=78
2023-10-27 14:45:05 root INFO Home.Outdoor.rf_status=57
2023-10-27 14:45:05 root INFO Home.Outdoor.reachable=1
2023-10-27 14:45:05 root INFO Home.Outdoor.time_utc=467649474
2023-10-27 14:45:05 root INFO Home.Outdoor.Temperature=13.7
2023-10-27 14:45:05 root INFO Home.Outdoor.Humidity=97
2023-10-27 14:45:05 root INFO Home.Outdoor.min_temp=10.5
2023-10-27 14:45:05 root INFO Home.Outdoor.max_temp=13.7
2023-10-27 14:45:05 root INFO Home.Outdoor.date_max_temp=467649167
2023-10-27 14:45:05 root INFO Home.Outdoor.date_min_temp=467629838
2023-10-27 14:45:05 root INFO Home.Outdoor.temp_trend=1
2023-10-27 14:45:05 root CRITICAL 'module_name'
Traceback (most recent call last):
File "/opt/loxberry/data/plugins/netatmo-weather/netatmo.py", line 505, in
main(args)
File "/opt/loxberry/data/plugins/netatmo-weather/netatmo.py", line 310, in main
value = "{0}.{1}.{2}={3}".format(device["home_name"], module["module_name"], "battery_percent",
KeyError: 'module_name'
```

**Comment by rettroo** [comment]
similar issue here:

2023-11-22 19:15:01 root INFO using plugin log file /opt/loxberry/log/plugins/netatmo-weather/netatmo-weather.log
2023-11-22 19:15:01 root INFO using system configuration file /opt/loxberry/config/system/general.json
2023-11-22 19:15:01 root INFO Miniserver ip address: 10.0.1.8
2023-11-22 19:15:01 root INFO No session cookie file found. /opt/loxberry/data/plugins/netatmo-weather/netatmo-weather.cookie
2023-11-22 19:15:01 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): auth.netatmo.com:443
2023-11-22 19:15:01 urllib3.connectionpool DEBUG https://auth.netatmo.com:443 "GET /en-us/access/login HTTP/1.1" 200 None
2023-11-22 19:15:01 root INFO Successfully got session cookie from https://auth.netatmo.com/en-us/access/login
2023-11-22 19:15:02 urllib3.connectionpool DEBUG https://auth.netatmo.com:443 "GET /access/csrf HTTP/1.1" 200 52
2023-11-22 19:15:02 root INFO Found _token value t9aWTUphozJCerqF4O8MU8HMYRpHUVYrOroKlhWu in response from https://auth.netatmo.com/access/csrf
2023-11-22 19:15:03 urllib3.connectionpool DEBUG https://auth.netatmo.com:443 "POST /access/postlogin?next_url=https%3A%2F%2Fmy.netatmo.com%2Fapp%2Fstation%2F HTTP/1.1" 302 634
2023-11-22 19:15:04 urllib3.connectionpool DEBUG https://auth.netatmo.com:443 "GET /access/keychain?next_url=https%3A%2F%2Fmy.netatmo.com%2Fapp%2Fstation%2F HTTP/1.1" 302 658
2023-11-22 19:15:05 urllib3.connectionpool DEBUG https://auth.netatmo.com:443 "GET /en-us/access/keychain?next_url=https%3A%2F%2Fmy.netatmo.com%2Fapp%2Fstation%2F HTTP/1.1" 200 None
2023-11-22 19:15:05 root INFO Successfully logged in using username hoch@gmx.at and password xxxxxxxxxx to https://auth.netatmo.com/access/postlogin
2023-11-22 19:15:05 root INFO Found netatmocomaccess_token value 638a76924bca25ebb40022f5%7C798669d47c04c588f6277d4d51fdee70 in response from https://auth.netatmo.com/access/postlogin
2023-11-22 19:15:05 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): api.netatmo.com:443
2023-11-22 19:15:06 urllib3.connectionpool DEBUG https://api.netatmo.com:443 "POST /api/getstationsdata HTTP/1.1" 200 None
2023-11-22 19:15:06 root INFO Querying queried API https://api.netatmo.com/api/getstationsdata
2023-11-22 19:15:06 root INFO Successfully queried queried API https://api.netatmo.com/api/getstationsdata
2023-11-22 19:15:06 root CRITICAL 'module_name'
Traceback (most recent call last):
File "/opt/loxberry/data/plugins/netatmo-weather/netatmo.py", line 505, in
main(args)
File "/opt/loxberry/data/plugins/netatmo-weather/netatmo.py", line 234, in main
value = "{0}.{1}.{2}={3}".format(device["home_name"], device["module_name"], "wifi_status",
KeyError: 'module_name'

**Comment by michaelmiklis** [comment]
Cloud you please try the updated netatmo.py file in this repo (just updated) and check again?

Start the Plugin with and post the unnamed module (should be displayed as NAModuleX_HEX-Zahlen=
