### ISSUE TITLE
KeyError: 'module_name' in basestation

### ISSUE THREAD

**Issue by rettroo** [michaelmiklis/loxberry-plugin-netatmo-weather#4]
no chance to get data out...
KeyError: 'module_name'
any idea?

`
2023-11-22 19:15:01 root INFO using plugin log file /opt/loxberry/log/plugins/netatmo-weather/netatmo-weather.log
2023-11-22 19:15:01 root INFO using system configuration file /opt/loxberry/config/system/general.json
2023-11-22 19:15:01 root INFO Miniserver ip address: 10.0.1.8
2023-11-22 19:15:01 root INFO No session cookie file found. /opt/loxberry/data/plugins/netatmo-weather/netatmo-weather.cookie
2023-11-22 19:15:01 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): auth.netatmo.com:443
2023-11-22 19:15:01 urllib3.connectionpool DEBUG https://auth.netatmo.com:443 "GET /en-us/access/login HTTP/1.1" 200 None
2023-11-22 19:15:01 root INFO Successfully got session cookie from https://auth.netatmo.com/en-us/access/login
2023-11-22 19:15:02 urllib3.connectionpool DEBUG https://auth.netatmo.com:443 "GET /access/csrf HTTP/1.1" 200 52
2023-11-22 19:15:02 root INFO Found _token value t9aWTUphozJCerqF4O8MU8HMYRpHUVYrOroKlhWu in response from https://auth.netatmo.com/access/csrf
2023-11-22 19:15:03 urllib3.connectionpool DEBUG https://auth.netatmo.com:443 "POST /access/postlogin?next_url=https%3A%2F%2Fmy.netatmo.com%2Fapp%2Fstation%2F HTTP/1.1" 302 634
2023-11-22 19:15:04 urllib3.connectionpool DEBUG https://auth.netatmo.com:443 "GET /access/keychain?next_url=https%3A%2F%2Fmy.netatmo.com%2Fapp%2Fstation%2F HTTP/1.1" 302 658
2023-11-22 19:15:05 urllib3.connectionpool DEBUG https://auth.netatmo.com:443 "GET /en-us/access/keychain?next_url=https%3A%2F%2Fmy.netatmo.com%2Fapp%2Fstation%2F HTTP/1.1" 200 None
2023-11-22 19:15:05 root INFO Successfully logged in using username hoch@gmx.at and password xxxxxxxxxx to https://auth.netatmo.com/access/postlogin
2023-11-22 19:15:05 root INFO Found netatmocomaccess_token value 638a76924bca25ebb40022f5%7C798669d47c04c588f6277d4d51fdee70 in response from https://auth.netatmo.com/access/postlogin
2023-11-22 19:15:05 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): api.netatmo.com:443
2023-11-22 19:15:06 urllib3.connectionpool DEBUG https://api.netatmo.com:443 "POST /api/getstationsdata HTTP/1.1" 200 None
2023-11-22 19:15:06 root INFO Querying queried API https://api.netatmo.com/api/getstationsdata
2023-11-22 19:15:06 root INFO Successfully queried queried API https://api.netatmo.com/api/getstationsdata
2023-11-22 19:15:06 root CRITICAL 'module_name'
Traceback (most recent call last):
File "/opt/loxberry/data/plugins/netatmo-weather/netatmo.py", line 505, in
main(args)
File "/opt/loxberry/data/plugins/netatmo-weather/netatmo.py", line 234, in main
value = "{0}.{1}.{2}={3}".format(device["home_name"], device["module_name"], "wifi_status",
KeyError: 'module_name'
`

**Comment by rettroo** [comment]
schade das es hier keinen support gibt...

**Comment by michaelmiklis** [comment]
@rettroo  kannst du es mal mit der aktualisierten netatmo.py probieren (ich habe gerade ein Commit gemacht)

Der Fehler kommt durch Module ohne Namen - keine Ahnung warum es das neuerdings gibt.

Führ danach das Pluginmal aus und poste was es für ein Modul bei dir ist (erkennbar am Modulnamen NAModuleX_HEX-Zahlen
